// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Loading: typeof import('./src/components/loading.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    Thread: typeof import('./src/components/thread.vue')['default']
    Thread_list: typeof import('./src/components/thread_list.vue')['default']
  }
}
